### ISSUE TITLE
SIG-Core 11/30 release notes

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-core#18]
Please fill any info related to the below for the 11/30 release notes: Note this has a due date of Friday Nov 12th, 2021

 ### Features
 ### Bug fixes (GHI list if possible)
 ### Deprecations
 ### Known issues

**Comment by lumberyard-employee-dm** [comment]
O3DE as an SDK
---
### Features
- Added Engine SDK layout support for Linux and Mac: https://github.com/o3de/o3de/issues/3189, https://github.com/o3de/o3de/issues/3192
- Added support for installing non-monolithic and monolithic artifacts into the same Engine SDK layout: https://github.com/o3de/o3de/issues/3227
- Added support for installing a Project Game Release Layout(Windows, Linux, MacOS): https://github.com/o3de/o3de/issues/3201
- Added ComponentApplication Lifecycle Events to facilitate startup configuration for the GameLauncher: https://github.com/o3de/o3de/commit/b3b646dad9c16d4a93cf1058034329c615c1a54b
- Updated the AssetBundler to use AZ::IO::Archive for creation of Pak Files: https://github.com/o3de/o3de/issues/3419
- Improved Error messags in the project's EngineFinder.cmake to help with indicating why the project could not locate the engine: https://github.com/o3de/o3de/pull/4713
- Added Multi-Config/Multi-Permutation support to the installer. This adds support for build configurations like debug, profile, release can be placed in the same installer. This also allows non-monolithic(Default) and monolithic(Monolithic) permutations to be added to the installer: https://github.com/o3de/o3de/pull/5062
- Limit the configuration types available in the Engine SDK layout to only the configurations that were built. i.e If the SDK was only built with the profile configuration, only the profile configuration will be available when using the SDK with a project: https://github.com/o3de/o3de/issues/2526

### Bug fixes
- Resolved issues with required gems not being treated as required when using an Engine SDK: https://github.com/o3de/o3de/issues/3430
- Fixed issue "Relocating the Project Game Release Layout outside of the install directory fails to initialize": https://github.com/o3de/o3de/commit/627012840d62a8f10fd6a7c595bac0b68d936f4b
- Fixed for launching the Editor through ProjectManager on Mac as well as other miscellaneous Project Manager fixes.: https://github.com/o3de/o3de/pull/5264
- Fixed level creation on Linux: https://github.com/o3de/o3de/pull/3488
- Fixed rpaths when using an Engine SDK layout on Linux: https://github.com/o3de/o3de/pull/3370
- Added fix for Android Monolithic release builds: https://github.com/o3de/o3de/pull/3788
- Fixed issue where CMake targets which were wrapped in two layers of generator expressions could not be added as dependencies when using an Engine SDK layout: https://github.com/o3de/o3de/pull/2337/files

### Deprecations
- Updated the FileIO Aliases to provide more accurate descriptions of the paths they represent: https://github.com/o3de/o3de/issues/4183, Impactful Change link: https://discord.com/channels/805939474655346758/852574203437121586/895059153247170590
- The AssetProcessor Exclude Filters are now treated relative to the Scan Folder: https://github.com/o3de/o3de/issues/4044 Impactful Change link: https://discord.com/channels/805939474655346758/852574203437121586/902248898683363400
- The `--project-path` parameter is now treated relative to the current working directory in C++ Applications: https://github.com/o3de/o3de/pull/5194 Impactful Change link: https://discord.com/channels/805939474655346758/852574203437121586/905874057998766161
- Rewrote the AzToolsFramework ArchiveComponent to use the AZ::IO::Archive instead of 7za.exe. 7za.exe has been removed from the code base https://github.com/o3de/o3de/pull/4332

**Comment by amznestebanpapp** [comment]
### Features
- Better compiler detection on Linux. Passing `CMAKE_C_COMPILER` and  `CMAKE_CXX_COMPILER` is no longer required. https://github.com/o3de/o3de/pull/5376
- Support for multiple configurations and monolithic into the SDK https://github.com/o3de/o3de/pull/5062
- Adds stack traces to exception handling https://github.com/o3de/o3de/pull/4708
- Enabled override/virtual warnings https://github.com/o3de/o3de/pull/4071
- Limit configuration types a project sees when using an engine SDK https://github.com/o3de/o3de/pull/4033
- Enabled format securty warnings https://github.com/o3de/o3de/pull/3937
- Set MSVC compiler into permissive mode https://github.com/o3de/o3de/pull/3701
- Improvements to input dependency tracking in runtime dependencies https://github.com/o3de/o3de/pull/3665
- Enabled multiple warnings in MSVC and Clang https://github.com/o3de/o3de/pull/3378 https://github.com/o3de/o3de/pull/3376 https://github.com/o3de/o3de/pull/3352 https://github.com/o3de/o3de/pull/3033 https://github.com/o3de/o3de/pull/2925
- Adds support to compile with ASan https://github.com/o3de/o3de/pull/3292
- Adds helper RUN targets in project-centric workflow https://github.com/o3de/o3de/pull/2635

### Bug fixes
- Fixes for CMake 3,22rc https://github.com/o3de/o3de/pull/5314
- LuaIDE->GridHub dependency added https://github.com/o3de/o3de/pull/5229
- Editor->LuaIDE dependency added https://github.com/o3de/o3de/pull/4514
- XCode generation fails https://github.com/o3de/o3de/issues/3832
- It is not possible to create new Projects https://github.com/o3de/o3de/issues/3443
- runtime dependencies do not add target file dependencies https://github.com/o3de/o3de/issues/3391
- Jinja files are not being copied to install layout https://github.com/o3de/o3de/issues/2517
- Some projects are being re-processed in VS despite being clean https://github.com/o3de/o3de/issues/2288
- PhysX Gem can't be used as build dependency in engine SDK https://github.com/o3de/o3de/issues/2126
- 3rdParty runtime dependencies copied multiple times https://github.com/o3de/o3de/issues/2045 https://github.com/o3de/o3de/issues/1971

### Deprecations
- Removes VTUNE profiler hooks from Cry  https://github.com/o3de/o3de/pull/5291
- Removes cry load dll functions  https://github.com/o3de/o3de/pull/5295
- Renamed PHYSX_ENABLE_RUNNING_BENCHMARKS to LY_PHYSX_ENABLE_RUNNING_BENCHMARKS https://github.com/o3de/o3de/pull/5118
- Removes old "Integ" type of tests https://github.com/o3de/o3de/pull/4688
- Removes crcfix https://github.com/o3de/o3de/pull/3294
- Changed LY_UNITY_BUILD default to ON https://github.com/o3de/o3de/pull/3244
- Removes CryString and related classes https://github.com/o3de/o3de/pull/2757
